name: DevSecOps Pipeline

on:
  #workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security_scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. SCA (Software Composition Analysis)
      - name: Dependency Scan (Safety)
        run: |
          pip install safety
          safety check -r requirements.txt
          #safety scan -r requirements.txt

      # 2. SAST (Static Analysis)
      - name: Static Analysis (Bandit)
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-results.json || true

      # 3. Linting
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build_push_and_scan:
    needs: security_scans
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- uses: actions/checkout@v3
      #- name: Build, Tag, and Push
      #  run: |
      #   echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #   sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest .
      #   sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
     # - name: Set up Docker Buildx
     #   uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
         # context: .
          push: true 
          tags: ${{secrets.DOCKERHUB_USERNAME }}/flask-app:v1
          #file: ./Dockerfile

      #- name: Build Docker Image
      #  run: |
      #   sudo docker build --no-cache --progress=plain -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }} .
      #- name: Push to docker hub 
      #  run: |
      #   #echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #   docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}
          

      # 4. Container Scan (Trivy)
      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          #image-ref: 'flask-app:${{ github.sha }}'
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}
          format: 'table'
          exit-code: '1' # Fails build if vulnerabilities are found
          severity: 'CRITICAL,HIGH'
      

  deploy:
    needs: build_push_and_scan
    runs-on: self-hosted
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
            sudo docker pull flask-app:latest
            sudo docker stop flask-app || true
            sudo docker rm flask-app || true
            sudo docker run -d --name flask-app -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

  dast_scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # 5. DAST (OWASP ZAP)
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://${{ secrets.EC2_IP }}'
